In [31]:
import pandas as pd
from io import StringIO

In [32]:
# raw 데이터 생성
data = """
Timestamp,Name,CPUPerc,MemPerc,MemUsed
2025-02-28 16:09:31+09:00,LB,1.00,1.00,1.00
2025-02-28 16:09:32+09:00,LB,0.50,0.50,0.50
2025-02-28 16:10:33+09:00,AGENT,1.00,1.00,1.00
2025-02-28 16:10:33+09:00,AGENT,0.50,0.50,0.50
2025-02-28 16:09:41+09:00,LB,1.00,1.00,1.00
2025-02-28 16:09:42+09:00,LB,0.50,0.50,0.50
2025-02-28 16:10:43+09:00,AGENT,1.00,1.00,1.00
2025-02-28 16:10:43+09:00,AGENT,0.50,0.50,0.50
2025-02-28 16:10:59+09:00,AGENT,0.50,0.50,0.50
2025-02-28 16:11:01+09:00,AGENT,0.50,0.50,0.50
"""

In [33]:
df = pd.read_csv(StringIO(data), parse_dates=['Timestamp'])

In [34]:
df

                  Timestamp   Name  CPUPerc  MemPerc  MemUsed
0 2025-02-28 16:09:31+09:00     LB      1.0      1.0      1.0
1 2025-02-28 16:09:32+09:00     LB      0.5      0.5      0.5
2 2025-02-28 16:10:33+09:00  AGENT      1.0      1.0      1.0
3 2025-02-28 16:10:33+09:00  AGENT      0.5      0.5      0.5
4 2025-02-28 16:09:41+09:00     LB      1.0      1.0      1.0
5 2025-02-28 16:09:42+09:00     LB      0.5      0.5      0.5
6 2025-02-28 16:10:43+09:00  AGENT      1.0      1.0      1.0
7 2025-02-28 16:10:43+09:00  AGENT      0.5      0.5      0.5
8 2025-02-28 16:10:59+09:00  AGENT      0.5      0.5      0.5
9 2025-02-28 16:11:01+09:00  AGENT      0.5      0.5      0.5

In [35]:
df.set_index('Timestamp', inplace=True)

# Name별로 그룹화 후, 각 그룹에서 10초 단위로 리샘플링하여 평균 계산
df_resampled = df.groupby('Name').resample('10s').mean(numeric_only=True)
#df_resampled = df.resample('10s').mean(numeric_only=True)

# groupby 후 resample을 하면 기존 index가 유지되므로, 'Name'을 인덱스로 가져오기 위해 reset_index()
df_resampled = df_resampled.reset_index()

In [36]:
df_resampled

    Name                 Timestamp  CPUPerc  MemPerc  MemUsed
0  AGENT 2025-02-28 16:10:30+09:00     0.75     0.75     0.75
1  AGENT 2025-02-28 16:10:40+09:00     0.75     0.75     0.75
2  AGENT 2025-02-28 16:10:50+09:00     0.50     0.50     0.50
3  AGENT 2025-02-28 16:11:00+09:00     0.50     0.50     0.50
4     LB 2025-02-28 16:09:30+09:00     0.75     0.75     0.75
5     LB 2025-02-28 16:09:40+09:00     0.75     0.75     0.75

In [37]:
print(df_resampled.to_csv(index=False))

Name,Timestamp,CPUPerc,MemPerc,MemUsed
AGENT,2025-02-28 16:10:30+09:00,0.75,0.75,0.75
AGENT,2025-02-28 16:10:40+09:00,0.75,0.75,0.75
AGENT,2025-02-28 16:10:50+09:00,0.5,0.5,0.5
AGENT,2025-02-28 16:11:00+09:00,0.5,0.5,0.5
LB,2025-02-28 16:09:30+09:00,0.75,0.75,0.75
LB,2025-02-28 16:09:40+09:00,0.75,0.75,0.75