In [8]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("01_numpy_ng.csv")
# DateTime을 한국 시간(KST)으로 변환
df['DateTime'] = pd.to_datetime(df['DateTime'])
df['DateTime'] = df['DateTime'].dt.tz_localize('UTC').dt.tz_convert('Asia/Seoul')
df.head(3)

,DateTime,vuser,Tests,Errors,Mean_Test_Time_(ms),Test_Time_Standard_Deviation_(ms),TPS,Mean_response_length,Response_bytes_per_second,Response_errors,Mean_time_to_resolve_host,Mean_time_to_establish_connection,Mean_time_to_first_byte
0,2025-02-28 16:11:21+09:00,10,17,0,1051.353,70.869,8.5,82.824,704.0,0,0,7.000,19.235
1,2025-02-28 16:11:23+09:00,20,45,0,995.489,56.031,22.5,83.111,1870.0,0,0,0.667,4.467
2,2025-02-28 16:11:25+09:00,20,42,0,1007.929,61.928,21.0,83.238,1748.0,0,0,0.571,4.381

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DateTime                           294 non-null    datetime64[ns, Asia/Seoul]
 1   vuser                              294 non-null    int64
 2   Tests                              294 non-null    int64
 3   Errors                             294 non-null    int64
 4   Mean_Test_Time_(ms)                294 non-null    float64
 5   Test_Time_Standard_Deviation_(ms)  294 non-null    float64
 6   TPS                                294 non-null    float64
 7   Mean_response_length               294 non-null    float64
 8   Response_bytes_per_second          294 non-null    float64
 9   Response_errors                    294 non-null    int64
 10  Mean_time_to_resolve_host          294 non-null    int64
 11  Mean_time_to_establish_connection  294 non-null    float64
 12  Mean_time_to_first_byte            294 non-null    float64
dtypes: datetime64[ns, Asia/Seoul](1), float64(7), int64(5)
memory usage: 30.0 KB

In [11]:
df.describe()

,vuser,Tests,Errors,Mean_Test_Time_(ms),Test_Time_Standard_Deviation_(ms),TPS,Mean_response_length,Response_bytes_per_second,Response_errors,Mean_time_to_resolve_host,Mean_time_to_establish_connection,Mean_time_to_first_byte
count,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.0,294.0,294.000000,294.000000
mean,602.721088,756.500000,213.693878,1316.669670,127.956269,378.250000,81.900466,30892.221088,0.0,0.0,0.226316,310.819575
std,323.955961,319.962474,341.057983,355.752426,97.715612,159.981237,0.805188,12959.300055,0.0,0.0,0.522389,353.981740
min,10.000000,17.000000,0.000000,989.644000,54.110000,8.500000,81.043000,704.000000,0.0,0.0,-5.392000,-12.960000
25%,320.000000,554.000000,0.000000,1007.842250,65.828250,277.000000,81.185500,22515.125000,0.0,0.0,0.168000,5.721250
50%,628.000000,823.000000,0.000000,1159.581000,79.542500,411.500000,81.345000,33568.750000,0.0,0.0,0.189500,153.558500
75%,937.500000,984.000000,362.250000,1589.564000,156.644750,492.000000,82.802000,39961.625000,0.0,0.0,0.236000,556.132000
max,1000.000000,1756.000000,1647.000000,2209.334000,520.588000,878.000000,83.375000,71242.500000,0.0,0.0,7.000000,1215.450000

# 10초 단위로 맞추기

In [12]:
# DateTime을 인덱스로 설정
df.set_index('DateTime', inplace=True)

# 10초 단위로 리샘플링하고 평균 계산
df_resampled = df.resample('10s').mean()

# 결과 출력
# print(df_resampled)

# 인덱스를 다시 컬럼으로 변환 (선택 사항)
df_resampled.reset_index(inplace=True)

# 최종 결과 출력
df_resampled.head(3)

,DateTime,vuser,Tests,Errors,Mean_Test_Time_(ms),Test_Time_Standard_Deviation_(ms),TPS,Mean_response_length,Response_bytes_per_second,Response_errors,Mean_time_to_resolve_host,Mean_time_to_establish_connection,Mean_time_to_first_byte
0,2025-02-28 16:11:20+09:00,21.4,40.6,0.0,1008.8180,61.2742,20.3,83.1368,1688.4,0.0,0.0,1.8794,7.3854
1,2025-02-28 16:11:30+09:00,41.8,77.4,0.0,1008.0502,66.7828,38.7,83.0932,3215.8,0.0,0.0,0.4696,4.1562
2,2025-02-28 16:11:40+09:00,61.6,116.4,0.0,1008.0578,61.1478,58.2,83.0164,4831.7,0.0,0.0,0.4424,4.2878

In [13]:
# pdm add pyarrow
df_resampled[['DateTime', 'TPS', 'vuser', 'Errors']].to_parquet('01_numpy_ng.parquet')

In [14]:
df = pd.read_parquet('01_numpy_ng.parquet')

In [16]:
df['DateTime'].min()

Timestamp('2025-02-28 16:11:20+0900', tz='Asia/Seoul')

In [17]:
df['DateTime'].max()

Timestamp('2025-02-28 16:21:00+0900', tz='Asia/Seoul')